export const PATH = {
  ROOT: '/',
  SIGNUP: '/sign-up',
  SIGNUP_COMPLETE: '/sign-up/complete',
  SIGNIN: '/sign-in',
  FIND_ACCOUNT: '/find-account',
  FIND_PLAYGROUND_FRIEND: '/find-playground-friend',
  CREATE_PLAYGROUND: '/create-playground',
  PLAYGROUND_SEARCH: '/playground-search',
  CREATE_PROFILE: '/create-profile',
  FRIEND_MESSAGE: (userId: string) => `/friend-message/${userId}`,
  PLAYGROUND_MESSAGE: (playgroundId: string) => `/playground-message/${playgroundId}`,
  PLAYGROUND_ROOM: (playgroundId: string) => `/playground-room/${playgroundId}`,
  EDIT_ACCOUNT: (userId: string) => `/edit-account/${userId}`,
  DELETE_ACCOUNT: (userId: string) => `/delete-account/${userId}`,
  EDIT_PROFILE: (userId: string) => `/edit-profile/${userId}`,
  PROFILE: (userId: string) => `/profile/${userId}`,
  FRIENDS_PLAYED: (userId: string) => `/friends-played/${userId}`,
  REPORT_FRIEND: (userId: string) => `/report-friend/${userId}`,
  DIRECT_MESSAGE: (userId: string) => `/direct-message/${userId}`,
  MY_RECRUITMENTS: (userId: string) => `/my-recruitments/${userId}`,
  FRIEND_RECOMMENDED: (userId: string) => `/friend-recommended/${userId}`,
  USER_SETTING: (userId: string) => `/user-setting/${userId}`,
  PROFILE_INFO: (userId: string) => `/profile-info/${userId}`,
  RELOAD: 0,
} as const;
